version: "3.9"

services: 
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: github
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts/data-load/init_clickhouse.sql:/docker-entrypoint-initdb.d/init.sql
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8005:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
  seed-job:
    build:
      context: .
      dockerfile: Dockerfile.seed
    depends_on:
      clickhouse:
          condition: service_healthy
      dynamodb-local:
          condition: service_started
    environment:
      - CLICKHOUSE_HOST=clickhouse

  indexer-service:
    build:
      context: ./apps/indexer-service
    container_name: indexer-service
    depends_on:
      clickhouse:
         condition: service_healthy
      embedding-service:
          condition: service_started
      opensearch:
          condition: service_started
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
  
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Opensearch2026!Aa
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        - CMD-SHELL
        - curl -k -u "admin:Opensearch2026!Aa" https://localhost:9200 || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s

  opensearch-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    container_name: opensearch-init
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOST=opensearch
    restart: "no"

  api-gateway:
    build: ./apps/api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - RAG_SERVICE_URL=http://rag-service:8001
    depends_on:
      - rag-service

  rag-service:
    build: ./apps/rag-service
    container_name: rag-service
    ports:
      - "8001:8001"
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DB: github
      EMBEDDING_SERVICE: http://embedding-service:8002/embed
      OPENSEARCH_HOST: opensearch
    depends_on:
      - clickhouse
      - opensearch

  embedding-service:
    build: ./apps/embedding-service
    container_name: embedding-service
    ports:
      - "8002:8002"
    environment:
      - OPENSEARCH_HOST=opensearch

volumes:
  clickhouse_data:
  opensearch_data:
  dynamodb_data: