namespace: ai-analytics

name: ollama


image:

  repository: ollama

  name: ollama

  tag: latest

  pullPolicy: IfNotPresent


replicaCount: 1


containerPort: 11434


service:

  port: 11434


resources:

  requests:

    cpu: 500m

    memory: 1Gi

  limits:

    cpu: 2

    memory: 3Gi


ingress:

  enabled: false


env: {}


persistence:

  enabled: true

  storage: 20Gi

livenessProbe:
  httpGet:
    path: /api/tags
    port: 11434
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /api/tags
    port: 11434
  initialDelaySeconds: 10
  periodSeconds: 10

