namespace: ai-analytics

name: api-gateway

image:
  name: api-gateway
  tag: v1.0.0
  pullPolicy: Always

replicaCount: 2

containerPort: 8000

service:
  port: 80

resources:

  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

ingress:

  enabled: false

  