apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-seed
spec:
  backoffLimit: 3

  template:

    spec:

      restartPolicy: Never

      containers:

        - name: clickhouse-seed

          image: bitnamilegacy/clickhouse:25.7.5-debian-12-r0

          command:
            - /bin/bash
            - -c

          args:
            - |
              apt-get update
              apt-get install -y python3 python3-pip

              pip3 install clickhouse-driver

              echo "Waiting for ClickHouse..."

              until clickhouse-client \
                --host clickhouse \
                --user admin \
                --password admin123 \
                --query "SELECT 1"
              do
                sleep 5
              done

              echo "Loading GitHub seed data"

              python3 /scripts/ingest_clickhouse.py

              echo "Seed complete"

          volumeMounts:

            - name: seed-script
              mountPath: /scripts

      volumes:

        - name: seed-script
          configMap:
            name: clickhouse-seed-script