name:  Docker Image Builder

on:

  push:
    branches:
      - level7

  workflow_dispatch:
    inputs:

      version:

        description: Image version

        required: true

        default: v1.0.0

permissions:
  contents: read

jobs:

  docker-build:

    uses: ./.github/workflows/docker-build.yml

    with:

      service: all
      
      version: ${{ inputs.version }}

    secrets: inherit