name: Deploy Dev


on:

  workflow_dispatch:

    inputs:

      image_tag:

        description: Docker image tag to deploy

        required: true

        type: string

        default: v1.0.0



permissions:

  contents: read



jobs:


  deploy-api-gateway:

    uses: ./.github/workflows/helm-deploy.yml

    with:

      service: api-gateway

      namespace: ai-analytics

      chart: api-gateway

      image_tag: ${{ inputs.image_tag }}

    secrets: inherit



  deploy-orchestrator-service:


    needs:

      - deploy-api-gateway


    uses: ./.github/workflows/helm-deploy.yml


    with:

      service: orchestrator-service

      namespace: ai-analytics

      chart: orchestrator-service

      image_tag: ${{ inputs.image_tag }}


    secrets: inherit



  deploy-rag-service:


    needs:

      - deploy-orchestrator-service


    uses: ./.github/workflows/helm-deploy.yml


    with:

      service: rag-service

      namespace: ai-analytics

      chart: rag-service

      image_tag: ${{ inputs.image_tag }}


    secrets: inherit



  deploy-embedding-service:


    needs:

      - deploy-rag-service


    uses: ./.github/workflows/helm-deploy.yml


    with:

      service: embedding-service

      namespace: ai-analytics

      chart: embedding-service

      image_tag: ${{ inputs.image_tag }}


    secrets: inherit



  deploy-indexer-service:


    needs:

      - deploy-embedding-service


    uses: ./.github/workflows/helm-deploy.yml


    with:

      service: indexer-service

      namespace: ai-analytics

      chart: indexer-service

      image_tag: ${{ inputs.image_tag }}


    secrets: inherit



  deploy-frontend:


    needs:

      - deploy-indexer-service


    uses: ./.github/workflows/helm-deploy.yml


    with:

      service: frontend

      namespace: ai-analytics

      chart: frontend

      image_tag: ${{ inputs.image_tag }}


    secrets: inherit