name:  Docker Image Build

on:
  push:
      branches:
        - level7
  workflow_dispatch:

permissions:
  contents: read

jobs:

  docker-build:

    uses: ./.github/workflows/docker-build.yml

    with:

      service: all

    secrets: inherit