name: Reusable Helm Deploy


on:

  workflow_call:

    inputs:

      service:

        description: Helm release name

        required: true

        type: string


      namespace:

        description: Kubernetes namespace

        required: false

        default: default

        type: string


      chart:

        description: Helm chart path or chart name

        required: true

        type: string


      repository:

        description: Helm repository URL

        required: false

        type: string


      values:

        description: Values file

        required: false

        type: string


      image_tag:

        description: Docker image tag

        required: false

        type: string

permissions:

  contents: read


jobs:


  helm-deploy:


    runs-on: ubuntu-latest


    env:

      AWS_REGION: us-east-1

      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com


    steps:


      - name: Checkout repository

        uses: actions/checkout@v4


      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ${{ env.AWS_REGION }}


      - name: Update kubeconfig

        run: |

          aws eks update-kubeconfig \
            --name ai-analytics-copilot \
            --region ${AWS_REGION}


      - name: Install Helm

        uses: azure/setup-helm@v4


      - name: Helm Deploy

        shell: bash

        run: |

          if [ -n "${{ inputs.repository }}" ]; then

            helm repo add platform \
            ${{ inputs.repository }}

            helm repo update

          fi


          VALUES=""

          if [ -n "${{ inputs.values }}" ]; then

            VALUES="-f ${{ inputs.values }}"

          fi


          IMAGE=""

          if [ -n "${{ inputs.image_tag }}" ]; then

            IMAGE="--set image.repository=${ECR_REGISTRY} \
                  --set image.tag=${{ inputs.image_tag }}"

          fi


          helm upgrade --install \
            ${{ inputs.service }} \
            ${{ inputs.chart }} \
            --namespace ${{ inputs.namespace }} \
            --create-namespace \
            ${VALUES} \
            ${IMAGE}


      - name: Verify deployment

        run: |

          kubectl rollout status deployment/${{ inputs.service }} \
            -n ${{ inputs.namespace }}
