name: Kubectl Apply


on:

  workflow_call:

    inputs:

      namespace:

        required: true

        type: string


      manifests:

        required: true

        type: string

      image_tag:

        required: false

        default: v1.0.0

        type: string
      

jobs:

  apply:

    runs-on: ubuntu-latest

    env:

      AWS_REGION: us-east-1

      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      IMAGE_TAG: ${{ inputs.image_tag }}


    steps:


      - name: Checkout

        uses: actions/checkout@v4


      - name: Configure AWS

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: us-east-1



      - name: Update kubeconfig

        run: |

          aws eks update-kubeconfig \
          --name ai-analytics-copilot \
          --region us-east-1



      - name: Apply manifests

        shell: bash

        run: |

          while IFS= read -r manifest
          do

            if [ -n "$manifest" ]; then

              if grep -q "kind: Job" "$manifest"; then

                  JOB_NAME=$(kubectl apply \
                    --dry-run=client \
                    -f "$manifest" \
                    -o jsonpath='{.metadata.name}')

                  echo "Processing job: ${JOB_NAME}"

                  kubectl delete job ${JOB_NAME} \
                    -n ${{ inputs.namespace }} \
                    --ignore-not-found=true

                  echo "Applying ${manifest}"

                  envsubst < "$manifest" | kubectl apply -f -

                  echo "Waiting for job ${JOB_NAME} to complete"

                  kubectl wait \
                    --for=condition=complete \
                    job/${JOB_NAME} \
                    -n ${{ inputs.namespace }} \
                    --timeout=1800s

                  echo "Logs for ${JOB_NAME}"

                  kubectl logs \
                    job/${JOB_NAME} \
                    -n ${{ inputs.namespace }}

              else

                  echo "Applying ${manifest}"

                  envsubst < "$manifest" | kubectl apply -f -

              fi

            fi

          done <<< "${{ inputs.manifests }}"
