name: Kubectl Apply


on:

  workflow_call:

    inputs:

      namespace:

        required: true

        type: string


      manifests:

        required: true

        type: string



jobs:

  apply:

    runs-on: ubuntu-latest


    steps:


      - name: Checkout

        uses: actions/checkout@v4


      - name: Configure AWS

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: us-east-1



      - name: Update kubeconfig

        run: |

          aws eks update-kubeconfig \
          --name ai-analytics-copilot \
          --region us-east-1



      - name: Apply manifests

        run: |

          echo "${{ inputs.manifests }}" | while read manifest
          do
             kubectl apply -f $manifest \
             -n ${{ inputs.namespace }}
          done



      - name: Wait for job

        run: |

          kubectl wait \
          --for=condition=complete \
          job/clickhouse-init \
          -n ${{ inputs.namespace }} \
          --timeout=300s