name: Terraform Plan

on:

  pull_request:
    branches:
      - main
      - level7

  push:
    branches:
      - level7
    #paths:
    #  - "terraform/**"

  workflow_dispatch:


permissions:

  contents: read
  id-token: write


env:

  AWS_REGION: us-east-1
  TF_WORKING_DIR: terraform/environments/dev


jobs:


  terraform-plan:


    name: Terraform Plan

    runs-on: ubuntu-latest


    steps:


      - name: Checkout repository

        uses: actions/checkout@v4



      - name: Configure AWS credentials using OIDC

        uses: aws-actions/configure-aws-credentials@v4

        with:

          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ai-analytics-copilot-github-actions

          aws-region: ${{ env.AWS_REGION }}



      - name: Verify AWS identity

        run: |

          aws sts get-caller-identity



      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3



      - name: Terraform Init

        working-directory: ${{ env.TF_WORKING_DIR }}

        run: |

          terraform init



      - name: Terraform Validate

        working-directory: ${{ env.TF_WORKING_DIR }}

        run: |

          terraform validate



      - name: Terraform Plan

        working-directory: ${{ env.TF_WORKING_DIR }}

        run: |

          terraform plan \
            -var-file=terraform.tfvars
